"""
Browsing personas for warming AdsPower profiles.

Four personas, each with 25+ unique hosts and 100+ search queries:
- Skin Trader — TF2 + Rust first, CS2 included
- Gift Cards / Game Keys — public keyshops (Eneba, G2G, U7BUY, …)
- Account Buyer — public account marketplaces (no checkout)
- AI Dev — Claude / OpenRouter / Cursor / GitHub first

No placing orders, no logging into seller panels, no real-money actions.
"""

import random
import logging
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


SKIN_TRADER = {
    "name": "Skin Trader",
    "custom_text_hint": "tf2 keys / rust skins / cs2 knife",
    "custom_label": "Game / item focus",
    "site_keywords": [
        "steamcommunity", "steampowered", "backpack.tf", "marketplace.tf",
        "mannco", "tf2", "teamfortress", "rust", "rustskins", "rustclash",
        "skin", "market", "trade", "inventory", "loadout", "unusual",
        "cs2", "csgo", "csfloat", "skinport", "dmarket", "bitskins",
        "csmoney", "cs.money", "skinbaron", "tradeit", "waxpeer",
        "gamerpay", "lis-skins", "shadowpay", "buff.market", "csgoroll",
        "csgoempire", "scrap.tf", "stntrading", "clash.gg", "loot.farm",
    ],
    "extra_sites": [
        "https://steamcommunity.com/market/",
        "https://store.steampowered.com",
        "https://backpack.tf",
        "https://marketplace.tf",
        "https://mannco.store",
        "https://tf2.tm",
        "https://scrap.tf",
        "https://trade.tf",
        "https://stntrading.eu",
        "https://wiki.teamfortress.com/wiki/Main_Page",
        "https://www.reddit.com/r/tf2trading/",
        "https://rust.tm",
        "https://rustskins.gg",
        "https://skinport.com",
        "https://rustclash.com",
        "https://clash.gg",
        "https://loot.farm",
        "https://csfloat.com",
        "https://dmarket.com",
        "https://bitskins.com",
        "https://cs.money",
        "https://skinbaron.de",
        "https://tradeit.gg",
        "https://waxpeer.com",
        "https://gamerpay.gg",
        "https://lis-skins.com",
        "https://shadowpay.com",
        "https://buff.market",
        "https://csgoroll.com",
        "https://csgoempire.com",
        "https://skinout.gg",
        "https://white.market",
    ],
    "priority_hosts": [
        "backpack.tf", "marketplace.tf", "mannco.store", "tf2.tm",
        "rust.tm", "rustskins.gg", "skinport.com",
    ],
    "base_queries": [
        "{item} price check",
        "buy {item} cheap",
        "sell {item} for real money",
        "best site to trade {item}",
        "{item} marketplace fees",
        "{item} steam market history",
        "is {item} a good investment",
        "{item} scam check",
    ],
    "fallback_queries": [
        "tf2 key price 2026",
        "best tf2 trading sites 2026",
        "backpack.tf unusual classifieds",
        "tf2 refined metal to keys",
        "is mannco.store legit",
        "marketplace.tf key price",
        "tf2 australium price",
        "tf2 strange weapons trading",
        "tf2 unusual effect tier list",
        "backpack.tf price guide tf2",
        "how to sell tf2 items for real money",
        "tf2 unusual hat price checker",
        "scrap.tf vs backpack.tf",
        "stntrading.eu review",
        "trade.tf classifieds tf2",
        "tf2.tm key price",
        "buy tf2 keys paypal",
        "cheapest tf2 unusual hats",
        "tf2 killstreak kit price",
        "tf2 professional killstreak",
        "tf2 festive weapons value",
        "tf2 collector unusual",
        "tf2 halloween spell unusual",
        "tf2 painted hats value",
        "tf2 vintage weapons trading",
        "tf2 craft hat price",
        "tf2 bills hat price",
        "tf2 max severed head",
        "tf2 burning flames unusual",
        "tf2 scorching unusual price",
        "is marketplace.tf safe 2026",
        "mannco.store fees explained",
        "tf2 steam market vs third party",
        "tf2 trading scam check",
        "sell tf2 keys real money",
        "tf2 refined price usd",
        "tf2 unusual trading discord",
        "tf2 australium rocket launcher",
        "tf2 strange professional scattergun",
        "backpack.tf vs mannco.store",
        "rust skins steam market",
        "best site to buy rust skins 2026",
        "rust ak skin prices",
        "rust item store rotation",
        "rust skins vs steam market fees",
        "rust skins marketplace comparison",
        "is rust.tm legit",
        "rustskins.gg review",
        "skinport rust skins",
        "rustclash skins marketplace",
        "loot.farm rust skins",
        "clash.gg rust review",
        "rust tempered ak skin",
        "rust forest raider ak",
        "rust glacier ak price",
        "rust handmade gun skins",
        "rust garage door skins",
        "rust sheet metal door skin",
        "rust sar skins steam",
        "rust mp5 skins price",
        "rust python revolver skins",
        "rust armored door skins",
        "how to sell rust skins 2026",
        "rust steam market 15 percent fee",
        "best rust skin marketplace 2026",
        "rust.tm vs skinport",
        "buy rust skins paypal",
        "rust skins instant delivery",
        "is rustclash legit",
        "rust item store skins worth it",
        "rust glowing skins list",
        "rust blackout skins",
        "rust skins real money",
        "csfloat vs skinport",
        "cs2 knife prices 2026",
        "buy cs2 skins cheap",
        "is csfloat legit 2026",
        "dmarket cs2 review",
        "bitskins cs2 fees",
        "cs.money trade cs2",
        "skinbaron cs2 germany",
        "tradeit.gg cs2 skins",
        "waxpeer cs2 marketplace",
        "gamerpay.gg review",
        "lis-skins.com review",
        "shadowpay cs2 skins",
        "buff.market cs2",
        "csgoroll vs csgoempire",
        "karambit doppler price 2026",
        "cs2 gloves prices",
        "awp dragon lore price",
        "cs2 cases roi 2026",
        "how to sell cs2 skins",
        "cs2 steam market vs third party",
        "best cs2 trading site 2026",
        "skinport cs2 fees",
        "is csfloat safe",
        "cs2 souvenir skins",
        "cs2 sticker craft value",
        "ak redline cs2 price",
        "awp asiimov cs2",
        "cs2 butterfly knife price",
        "cs2 float checker",
        "white.market cs2",
        "skinout.gg review",
    ],
    "query_keywords": [
        "tf2", "rust", "unusual", "key", "keys", "refined", "metal",
        "trade", "trading", "marketplace", "steam", "australium",
        "mannco", "backpack", "skin", "skins", "hat", "hats",
        "cs2", "csgo", "csfloat", "skinport", "dmarket", "knife",
        "karambit", "gloves", "ak", "awp",
    ],
    "interest_keywords": [
        "unusual", "unusuals", "hat", "hats", "keys", "key",
        "australium", "strange", "refined", "metal", "effect",
        "ak", "door", "rust", "skins", "tf2", "loadout",
        "knife", "karambit", "gloves", "cs2", "awp",
    ],
        "link_bias": {},
}


GIFT_CARDS = {
    "name": "Gift Cards / Game Keys",
    "custom_text_hint": "roblox / steam / apple / razer gold",
    "custom_label": "Gift brand / game",
    "site_keywords": [
        "u7buy", "eneba", "g2g", "kinguin", "cdkeys", "gamivo", "g2a",
        "k4g", "seagm", "offgamers", "instagaming", "hrkgame", "fanatical",
        "greenmangaming", "humblebundle", "gamesplanet", "dlgamer",
        "razer", "giftcard", "gift-card", "gift card", "codashop",
        "cardcash", "raise.com", "gg.deals", "isthereanydeal", "pcgamekeys",
        "nugamestore", "xbox.com", "playstation", "nintendo", "roblox",
    ],
    "extra_sites": [
        "https://www.u7buy.com",
        "https://www.eneba.com",
        "https://www.g2g.com",
        "https://www.kinguin.net",
        "https://www.cdkeys.com",
        "https://www.gamivo.com",
        "https://www.g2a.com",
        "https://k4g.com",
        "https://www.seagm.com",
        "https://www.offgamers.com",
        "https://www.instagaming.com",
        "https://www.hrkgame.com",
        "https://www.fanatical.com",
        "https://www.greenmangaming.com",
        "https://www.humblebundle.com",
        "https://www.gamesplanet.com",
        "https://www.dlgamer.com",
        "https://gold.razer.com",
        "https://www.xbox.com/en-US/gift-cards",
        "https://store.playstation.com",
        "https://www.nintendo.com/us/store/games/",
        "https://www.roblox.com/giftcards",
        "https://www.amazon.com/gift-cards/",
        "https://www.cardcash.com",
        "https://www.raise.com",
        "https://www.codashop.com",
        "https://gg.deals",
        "https://isthereanydeal.com",
        "https://www.pcgamekeys.com",
        "https://www.reddit.com/r/GameDeals/",
        "https://store.steampowered.com",
    ],
    "priority_hosts": [
        "u7buy.com", "eneba.com", "g2g.com", "kinguin.net", "cdkeys.com",
    ],
    "base_queries": [
        "buy {item} gift card",
        "{item} gift card instant delivery",
        "best site for {item} keys",
        "is {item} gift card shop legit",
        "{item} digital code cheap",
        "{item} vs steam official",
    ],
    "fallback_queries": [
        "buy roblox gift card",
        "buy apple gift card online",
        "buy razer gold gift card",
        "best gift card shops 2026",
        "fast digital gift card delivery",
        "eneba vs g2g steam keys",
        "u7buy gift cards review",
        "is kinguin legit 2026",
        "cdkeys steam key review",
        "gamivo vs eneba",
        "g2a steam keys safe",
        "k4g.com review",
        "seagm roblox gift card",
        "offgamers gift cards",
        "instagaming keys review",
        "hrkgame steam keys",
        "fanatical bundle keys",
        "green man gaming vs steam",
        "humble bundle keys",
        "gamesplanet cd keys",
        "dlgamer gift cards",
        "razer gold top up",
        "xbox gift card digital",
        "playstation store gift card",
        "nintendo eshop card",
        "amazon gift card online",
        "cardcash discounted gift cards",
        "raise.com gift cards",
        "codashop mobile game top up",
        "gg.deals cheapest keys",
        "isthereanydeal steam",
        "pcgamekeys review",
        "buy steam wallet code",
        "steam gift card cheap",
        "buy fortnite vbucks card",
        "buy league of legends rp card",
        "buy valorant points gift",
        "buy minecraft java key",
        "gta 5 cheap key",
        "elden ring key shop",
        "call of duty key cheap",
        "ea app game keys",
        "ubisoft connect keys",
        "epic games store keys",
        "windows 11 key shop",
        "office 365 key cheap",
        "spotify gift card",
        "netflix gift card digital",
        "google play gift card",
        "itunes gift card cheap",
        "best site steam keys 2026",
        "instant delivery steam key",
        "region locked steam keys",
        "global steam key vs eu",
        "eneba instant delivery",
        "g2g gift card sellers",
        "u7buy vs eneba",
        "is cdkeys safe",
        "kinguin seller ratings",
        "g2a shield worth it",
        "gamivo coupon codes",
        "fanatical daily deal",
        "humble choice vs keys",
        "razer gold pin",
        "roblox gift card 25",
        "roblox gift card 50",
        "buy roblox premium",
        "apple gift card no store visit",
        "xbox game pass gift",
        "ps plus gift card",
        "nintendo switch online card",
        "steam 20 wallet code",
        "steam 50 wallet code",
        "cheapest gta v key",
        "cheap rust steam key",
        "cheap rust game key",
        "cheap cs2 prime key",
        "battlefield key shop",
        "fifa points card",
        "nba 2k vc card",
        "free fire diamonds top up",
        "genshin genesis crystals shop",
        "honor of kings top up",
        "mobile legends diamonds",
        "pubg mobile uc",
        "codashop vs seagm",
        "offgamers vs g2g",
        "best razer gold shop",
        "buy steam keys reddit",
        "game deals gift cards",
        "digital game key comparison 2026",
        "avoid steam key scams",
        "official vs third party keys",
        "gift card instant email delivery",
        "buy playstation store credit",
        "buy nintendo eshop credit",
        "eneba gift cards roblox",
        "g2g roblox gift card",
        "u7buy steam wallet",
        "kinguin roblox",
        "cdkeys gift cards",
        "fast shops for game keys",
        "best digital keystores 2026",
        "legit cheap game keys",
        "steam key activation guide",
        "xbox gift card redeem",
        "how to redeem razer gold",
        "humblebundle gift games",
        "fanatical mystery keys",
        "greenmangaming loyalty",
        "gamesplanet weekly sale",
        "dlgamer loyalty points",
        "is g2a legit 2026",
        "eneba seller reputation",
        "u7buy instant ship gift cards",
    ],
    "query_keywords": [
        "gift", "giftcard", "gift card", "eneba", "g2g",
        "u7buy", "kinguin", "cdkeys", "roblox", "razer", "xbox",
        "playstation", "nintendo", "apple", "wallet", "top up", "digital",
        "gamivo", "g2a", "humble", "fanatical", "steam key", "steam wallet",
        "game key", "game keys", "keyshop",
    ],
    "interest_keywords": [
        "steam", "roblox", "gift", "key", "keys", "razer", "xbox",
        "playstation", "nintendo", "apple", "wallet", "bundle", "deal",
        "eneba", "g2g", "instant",
    ],
    "link_bias": {
        "gift": 3, "gift-card": 3, "keys": 3, "deals": 2, "store": 2,
        "catalog": 2, "sale": 2, "redeem": 2,
    },
}


ACCOUNT_BUYER = {
    "name": "Account Buyer",
    "custom_text_hint": "rust / steam / fortnite / wow",
    "custom_label": "Game / account type",
    "site_keywords": [
        "playerauctions", "g2g", "eldorado", "playerup", "funpay",
        "gameflip", "playerok", "igvault", "accs.market", "epicnpc",
        "ownedcore", "sythe", "white.market", "mmoga", "account",
        "accounts", "battle.net", "epicgames", "riotgames", "ubisoft",
        "ea.com", "blizzard", "fortnite", "steam.tools",
    ],
    "extra_sites": [
        "https://www.playerauctions.com",
        "https://www.g2g.com",
        "https://www.eldorado.gg",
        "https://www.playerup.com",
        "https://funpay.com",
        "https://www.gameflip.com",
        "https://playerok.com",
        "https://www.igvault.com",
        "https://accs.market",
        "https://www.epicnpc.com",
        "https://www.ownedcore.com",
        "https://www.sythe.org",
        "https://white.market",
        "https://www.mmoga.com",
        "https://steam.tools",
        "https://store.steampowered.com",
        "https://www.xbox.com",
        "https://www.playstation.com",
        "https://www.nintendo.com",
        "https://store.epicgames.com",
        "https://www.riotgames.com",
        "https://us.battle.net",
        "https://www.ubisoft.com",
        "https://www.ea.com",
        "https://www.fortnite.com",
        "https://worldofwarcraft.blizzard.com",
        "https://www.reddit.com/r/GameSale/",
        "https://www.u7buy.com",
        "https://www.eneba.com",
        "https://www.g2a.com",
    ],
    "priority_hosts": [
        "playerauctions.com", "g2g.com", "eldorado.gg", "playerup.com",
        "funpay.com", "gameflip.com",
    ],
    "base_queries": [
        "buy {item} account",
        "{item} account for sale",
        "is {item} account shop legit",
        "{item} account marketplace",
        "cheap {item} account",
        "{item} account middleman",
    ],
    "fallback_queries": [
        "buy rust account",
        "tf2 unusual account for sale",
        "cs2 inventory account",
        "playerauctions vs g2g",
        "is eldorado.gg legit",
        "steam account with games cheap",
        "wow account sale",
        "fortnite account marketplace",
        "middleman for game accounts",
        "playerup.com review",
        "funpay accounts review",
        "gameflip steam accounts",
        "playerok.com accounts",
        "igvault account shop",
        "accs.market review",
        "epicnpc account sales",
        "ownedcore account forum",
        "sythe.org accounts",
        "white.market accounts",
        "mmoga game accounts",
        "steam.tools inventory checker",
        "buy steam account 2026",
        "rust account with skins",
        "rust 3k hour account",
        "tf2 unusuals on account",
        "cs2 knife account",
        "valorant account ranked",
        "league of legends account",
        "overwatch 2 account",
        "gta 5 account with money",
        "minecraft account microsoft",
        "roblox account for sale",
        "genshin impact account",
        "honkai star rail account",
        "apex legends account",
        "warzone account",
        "fc 25 ultimate team account",
        "nba 2k account",
        "destiny 2 account",
        "path of exile account",
        "lost ark account",
        "new world account",
        "eso account sale",
        "ff14 account",
        "wow boosted account",
        "wow wrath classic account",
        "diablo 4 account",
        "hearthstone account",
        "battle.net account with games",
        "epic games account",
        "ubisoft account with games",
        "ea app account",
        "riot account marketplace",
        "steam family share vs account",
        "how to buy steam account safely",
        "playerauctions buyer protection",
        "g2g account sellers rating",
        "eldorado middleman",
        "funpay steam accounts russia",
        "is playerauctions safe 2026",
        "gameflip seller fees",
        "playerok vs funpay",
        "igvault vs playerauctions",
        "reddit game sale accounts",
        "steam account with rust and cs2",
        "cheap fortnite skins account",
        "og fortnite account",
        "rare steam account",
        "vac banned account meaning",
        "steam account with tf2 unusuals",
        "cs2 premier account",
        "faceit account sale",
        "premier rank cs2 account",
        "rust team account",
        "ark survival account",
        "palworld account",
        "helldivers 2 account",
        "black myth wukong account",
        "elden ring account",
        "steam level 10 account",
        "steam account with 100 games",
        "xbox account with game pass",
        "psn account with games",
        "nintendo switch account",
        "epic games stacked account",
        "riot valorant immortal account",
        "lol diamond account",
        "wow mythic plus account",
        "ff14 endgame account",
        "genshin c6 account",
        "star rail endgame account",
        "safe account marketplace 2026",
        "game account escrow",
        "avoid account sale scams",
        "playerauctions rust",
        "g2g rust account",
        "eldorado cs2 account",
        "playerup fortnite",
        "funpay wow gold accounts",
        "gameflip roblox",
        "u7buy game accounts",
        "eneba accounts section",
        "best site to buy game accounts",
        "steam account recovery after purchase",
        "change email steam account",
        "account marketplace fees compared",
        "legit wow account shops",
        "legit rust account shops",
        "cs2 inventory worth account",
        "tf2 backpack unusual account",
    ],
    "query_keywords": [
        "account", "accounts", "playerauctions", "eldorado", "playerup",
        "funpay", "gameflip", "g2g", "steam", "wow", "fortnite", "rust",
        "cs2", "tf2", "valorant", "middleman", "igvault", "playerok",
    ],
    "interest_keywords": [
        "steam", "rust", "tf2", "cs2", "fortnite", "wow", "account",
        "ranked", "skins", "unusual", "inventory", "valorant", "league",
        "games", "hours",
    ],
    "link_bias": {
        "accounts": 3, "account": 2, "marketplace": 2, "shop": 2,
        "catalog": 2, "offers": 2, "games": 2,
    },
}


AI_DEV = {
    "name": "AI Dev",
    "custom_text_hint": "claude / cursor / openrouter",
    "custom_label": "Model / stack",
    "site_keywords": [
        "claude", "anthropic", "openrouter", "cursor", "openai", "chatgpt",
        "grok", "gemini", "aistudio", "opencode", "huggingface", "groq",
        "together.ai", "perplexity", "poe.com", "vercel", "github",
        "stackoverflow", "dev.to", "pypi", "npmjs", "langchain",
        "windsurf", "codeium", "continue.dev",
    ],
    "extra_sites": [
        "https://claude.ai",
        "https://www.anthropic.com",
        "https://docs.anthropic.com",
        "https://openrouter.ai",
        "https://cursor.com",
        "https://docs.cursor.com",
        "https://github.com",
        "https://github.com/features/copilot",
        "https://chatgpt.com",
        "https://platform.openai.com",
        "https://openai.com",
        "https://x.ai",
        "https://gemini.google.com",
        "https://aistudio.google.com",
        "https://opencode.ai",
        "https://huggingface.co",
        "https://groq.com",
        "https://www.together.ai",
        "https://www.perplexity.ai",
        "https://poe.com",
        "https://vercel.com/ai",
        "https://stackoverflow.com",
        "https://dev.to",
        "https://pypi.org",
        "https://www.npmjs.com",
        "https://www.langchain.com",
        "https://windsurf.com",
        "https://www.continue.dev",
        "https://www.reddit.com/r/LocalLLaMA/",
        "https://docs.openrouter.ai",
        "https://python.org",
    ],
    "priority_hosts": [
        "claude.ai", "anthropic.com", "docs.anthropic.com",
        "openrouter.ai", "cursor.com", "docs.cursor.com", "github.com",
    ],
    "base_queries": [
        "{item} api pricing",
        "{item} vs claude",
        "{item} docs",
        "how to use {item}",
        "{item} changelog",
        "best {item} models",
    ],
    "fallback_queries": [
        "claude api pricing",
        "openrouter vs openai",
        "cursor composer",
        "anthropic claude docs",
        "github copilot vs cursor",
        "openrouter models list",
        "gemini api key",
        "grok x.ai api",
        "claude.ai chat",
        "anthropic api reference",
        "docs.anthropic.com messages",
        "openrouter.ai pricing",
        "openrouter free models",
        "cursor.com download",
        "cursor ide docs",
        "docs.cursor.com rules",
        "github copilot pricing",
        "github features copilot",
        "chatgpt plus vs api",
        "openai platform docs",
        "openai api pricing 2026",
        "x.ai grok api",
        "gemini 2.5 pro",
        "google ai studio",
        "aistudio.google.com",
        "opencode.ai review",
        "huggingface inference api",
        "groq llama api",
        "together.ai inference",
        "perplexity api",
        "poe.com bots",
        "vercel ai sdk",
        "stackoverflow python llm",
        "dev.to claude cursor",
        "pypi anthropic package",
        "npm ai sdk",
        "langchain vs llama index",
        "windsurf vs cursor",
        "continue.dev vscode",
        "local llama reddit",
        "claude system prompt",
        "claude projects",
        "claude artifacts",
        "anthropic prompt caching",
        "anthropic batch api",
        "openrouter claude",
        "openrouter openai compatible",
        "cursor tab vs copilot",
        "cursor agent mode",
        "cursor .cursorrules",
        "github actions ai",
        "github models marketplace",
        "chatgpt canvas",
        "openai realtime api",
        "openai structured outputs",
        "grok 4 api",
        "gemini grounding",
        "ai studio rate limits",
        "huggingface transformers",
        "huggingface spaces",
        "groq whisper api",
        "together mixtral",
        "perplexity sonar",
        "langchain python tutorial",
        "python uv package manager",
        "npm create next app ai",
        "how to use claude api",
        "how to use openrouter",
        "how to use cursor docs",
        "openrouter models ranking",
        "cheapest claude api",
        "claude sonnet vs opus",
        "cursor changelog",
        "anthropic news",
        "github copilot chat",
        "github copilot cli",
        "openai cookbook",
        "gemini api docs",
        "x.ai developer",
        "opencode terminal agent",
        "huggingface hub models",
        "best llm api 2026",
        "best coding agent 2026",
        "cursor vs windsurf vs copilot",
        "openrouter vs together",
        "claude computer use",
        "mcp servers cursor",
        "model context protocol",
        "anthropic mcp",
        "cursor mcp docs",
        "github awesome mcp",
        "dev.to openrouter",
        "stackoverflow openai python",
        "pypi openai",
        "npm @anthropic-ai/sdk",
        "vercel ai gateway",
        "docs.openrouter.ai",
        "claude.ai vs chatgpt",
        "cursor.com pricing",
        "github.com pricing copilot",
        "anthropic console",
        "openrouter playground",
        "cursor forum",
        "github discussions copilot",
        "llm eval harness",
        "prompt engineering claude",
        "tool use claude",
        "function calling openai",
        "json mode gemini",
        "streaming sse llm",
        "tiktoken vs anthropic tokenizer",
        "rate limits openrouter",
        "byok openrouter",
        "cursor bugbot",
        "github copilot workspace",
        "ai coding workflow 2026",
    ],
    "query_keywords": [
        "claude", "anthropic", "openrouter", "cursor", "openai", "chatgpt",
        "gemini", "grok", "github", "copilot", "llm", "api", "huggingface",
        "langchain", "docs", "pricing", "mcp",
    ],
    "interest_keywords": [
        "claude", "cursor", "openrouter", "docs", "api", "pricing",
        "models", "github", "copilot", "changelog", "playground",
        "quickstart", "mcp", "python", "sdk",
    ],
    "link_bias": {
        "docs": 4, "documentation": 4, "api": 4, "pricing": 4,
        "changelog": 4, "blog": 3, "models": 4, "playground": 4,
        "quickstart": 4, "github": 3, "reference": 3, "guide": 3,
        "console": 3, "platform": 3,
    },
}


SOCIAL_META = {
    "name": "Social / Meta",
    "custom_text_hint": "fashion / pinterest / news (optional)",
    "custom_label": "Lifestyle focus",
    "skip_auth_forms": True,
    "site_keywords": [
        "asos", "farfetch", "adidas", "nike", "zara", "hm.com", "zalando",
        "ssense", "uniqlo", "eneba", "pinterest", "tumblr", "instagram",
        "facebook", "meta.com", "ai.meta", "wikipedia", "youtube", "bbc",
        "cnn", "reuters", "guardian", "spotify", "imdb", "g2g", "weather",
        "apple.com",
    ],
    "extra_sites": [
        "https://www.asos.com",
        "https://www.farfetch.com",
        "https://www.adidas.com",
        "https://www.nike.com",
        "https://www.zara.com",
        "https://www.hm.com",
        "https://www.zalando.com",
        "https://www.ssense.com",
        "https://www.uniqlo.com",
        "https://www.eneba.com",
        "https://www.g2g.com",
        "https://www.pinterest.com",
        "https://www.tumblr.com",
        "https://ai.meta.com",
        "https://about.meta.com",
        "https://www.youtube.com",
        "https://www.wikipedia.org",
        "https://www.google.com/maps",
        "https://news.google.com",
        "https://www.bbc.com",
        "https://www.cnn.com",
        "https://www.reuters.com",
        "https://www.theguardian.com",
        "https://www.reddit.com",
        "https://weather.com",
        "https://www.apple.com",
        "https://open.spotify.com",
        "https://www.imdb.com",
        "https://help.instagram.com",
        "https://www.facebook.com/help",
        "https://www.instagram.com",
        "https://www.facebook.com",
        "https://www.meta.com",
    ],
    "priority_hosts": [
        "asos.com", "farfetch.com", "adidas.com", "pinterest.com",
        "eneba.com", "wikipedia.org", "youtube.com", "nike.com",
    ],
    "late_hosts": [
        "instagram.com", "facebook.com", "meta.com",
    ],
    "base_queries": [
        "{item} outfit ideas",
        "{item} sale",
        "best {item} 2026",
        "{item} pinterest",
    ],
    "fallback_queries": [
        "asos sale",
        "asos dresses",
        "asos sneakers men",
        "farfetch sneakers",
        "farfetch sale",
        "farfetch designer bags",
        "adidas gazelle",
        "adidas spezial",
        "adidas samba og",
        "nike dunks",
        "nike air force 1",
        "nike vomero",
        "zara new in",
        "zara coats",
        "hm basics",
        "hm linen shirt",
        "zalando sneakers",
        "zalando dresses",
        "ssense hoodies",
        "ssense sale",
        "uniqlo airism",
        "uniqlo heattech",
        "new balance 550",
        "converse chuck 70",
        "on running cloudmonster",
        "pinterest outfit ideas",
        "pinterest room decor",
        "pinterest wallpaper",
        "pinterest meal prep",
        "pinterest capsule wardrobe",
        "pinterest home office",
        "pinterest travel outfit",
        "pinterest nail art",
        "tumblr photography",
        "tumblr art blogs",
        "eneba gift cards",
        "eneba steam keys",
        "eneba vs g2g",
        "g2g marketplace",
        "is eneba legit",
        "bbc news",
        "bbc world",
        "cnn world",
        "reuters today",
        "the guardian news",
        "wikipedia featured article",
        "wikipedia science",
        "google maps nearby",
        "google news headlines",
        "weather this week",
        "weather weekend",
        "youtube trending",
        "youtube music mix",
        "spotify playlists",
        "spotify discover weekly",
        "imdb top movies",
        "imdb coming soon",
        "apple iphone",
        "apple airpods",
        "reddit popular",
        "reddit pictures",
        "meta ai",
        "meta llama",
        "about meta",
        "ai.meta.com",
        "meta newsroom",
        "llama open source",
        "instagram help center",
        "facebook help center",
        "how instagram stories work",
        "instagram download android",
        "facebook privacy basics",
        "instagram reels how it works",
        "asos delivery tracker",
        "nike running shoes 2026",
        "adidas spezial grey",
        "farfetch authentic",
        "pinterest interior design",
        "zalando outlet",
        "hm new arrivals",
        "zara shoes",
        "uniqlo ut graphic tees",
        "ssense designer sneakers",
        "bbc climate",
        "reuters markets",
        "guardian culture",
        "imdb tv series",
        "spotify podcasts",
        "youtube documentary",
        "wikipedia history",
        "google maps restaurants",
        "weather radar",
        "apple watch",
        "eneba xbox keys",
        "g2g gift cards",
        "pinterest wedding ideas",
        "tumblr fashion",
        "adidas originals hoodie",
        "nike tech fleece",
        "farfetch sunglasses",
        "asos winter coats",
        "cnn tech",
        "bbc sport",
        "meta llama 4",
        "about.meta.com company",
        "help.instagram.com privacy",
        "facebook.com help password",
        "new balance 990v6",
        "dr martens 1460",
        "levis 501 original",
        "zara man trousers",
        "asos design jeans",
        "farfetch luxury sneakers",
        "adidas samba white",
        "nike pegasus 41",
        "pinterest summer outfits",
        "pinterest kitchen ideas",
        "pinterest desk setup",
        "tumblr aesthetic blogs",
        "eneba playstation store",
        "is g2g safe 2026",
        "bbc business",
        "cnn europe",
        "reuters climate",
        "the guardian football",
        "wikipedia today's featured",
        "google maps traffic",
        "youtube workout mix",
        "spotify charts",
        "imdb oscar winners",
        "apple macbook air",
        "meta ai assistant",
        "about meta leadership",
    ],
    "query_keywords": [
        "asos", "farfetch", "adidas", "nike", "zara", "pinterest", "eneba",
        "wikipedia", "youtube", "bbc", "zalando", "uniqlo", "ssense", "hm",
        "spotify", "imdb", "tumblr", "guardian", "reuters", "cnn", "weather",
        "meta ai", "llama", "instagram", "facebook",
    ],
    "interest_keywords": [
        "sale", "sneakers", "outfit", "pinterest", "adidas", "nike", "asos",
        "news", "wikipedia", "youtube", "spotify", "help", "about", "blog",
        "gazelle", "dunks", "playlist",
    ],
    "link_bias": {
        "help": 3, "about": 3, "newsroom": 3, "blog": 2, "sale": 2,
        "new-in": 2, "features": 2, "privacy": 2,         "shop": 2,
    },
}


PERSONAS = [SKIN_TRADER, GIFT_CARDS, ACCOUNT_BUYER, AI_DEV, SOCIAL_META]


def get_persona_names() -> list:
    return [p["name"] for p in PERSONAS]


def get_persona_hints() -> dict:
    return {p["name"]: p.get("custom_text_hint", "") for p in PERSONAS}


def get_persona_labels() -> dict:
    return {p["name"]: p.get("custom_label", "Custom focus") for p in PERSONAS}


def persona_uses_custom_text(name: str) -> bool:
    return True


def _persona_by_name(name: str) -> dict:
    if not name:
        return SKIN_TRADER
    wanted = name.strip().lower()
    for p in PERSONAS:
        if p["name"].lower() == wanted:
            return p
    return SKIN_TRADER


def _host_key(url: str) -> str:
    raw = (url or "").strip()
    if not raw:
        return ""
    if "://" not in raw:
        raw = "https://" + raw
    try:
        host = urlparse(raw).netloc.lower().replace("www.", "")
    except Exception:
        host = raw.lower()
    return host.split(":")[0]


def assign_persona(profile_id: str, all_sites: list, all_queries: list,
                   forced_persona: str = None, custom_text: str = "") -> dict:
    """Assign a named persona and build a unique-host browsing pool.

    Pool = that persona's extra_sites + config sites that match its keywords.
    Unrelated config sites are not mixed in (gift-card runs stay off backpack.tf).
    """
    persona = _persona_by_name(forced_persona)

    persona_sites = []
    for site in all_sites or []:
        site_lower = (site or "").lower()
        if any(kw in site_lower for kw in persona["site_keywords"]):
            persona_sites.append(site)

    persona_queries = []
    for query in all_queries or []:
        query_lower = (query or "").lower()
        if any(kw in query_lower for kw in persona["query_keywords"]):
            persona_queries.append(query)

    final_sites = list(persona.get("extra_sites", []))
    final_sites.extend(persona_sites)

    reddit_sites = [s for s in final_sites if "reddit.com" in s.lower()]
    if len(reddit_sites) > 2:
        random.shuffle(reddit_sites)
        drop = set(reddit_sites[2:])
        final_sites = [s for s in final_sites if s not in drop]

    seen_hosts = set()
    deduped = []
    for s in final_sites:
        host = _host_key(s)
        if not host or host in seen_hosts:
            continue
        seen_hosts.add(host)
        deduped.append(s)
    final_sites = deduped
    random.shuffle(final_sites)

    priority = [h.lower().replace("www.", "") for h in persona.get("priority_hosts", [])]

    def _prio(url: str) -> int:
        host = _host_key(url)
        for i, ph in enumerate(priority):
            if host == ph or host.endswith("." + ph) or ph.endswith("." + host):
                return i
        return 100

    final_sites.sort(key=_prio)

    late = [h.lower().replace("www.", "") for h in persona.get("late_hosts", [])]
    if late:
        def _late_rank(url: str) -> int:
            host = _host_key(url)
            for ph in late:
                if host == ph or host.endswith("." + ph) or ph.endswith("." + host):
                    return 1
            return 0
        final_sites.sort(key=_late_rank)

    final_queries = list(persona_queries)
    _build_custom_queries(persona, custom_text, final_queries)
    final_queries.extend(persona.get("fallback_queries", []))

    seen_q = set()
    deduped_q = []
    for q in final_queries:
        key = (q or "").strip().lower()
        if not key or key in seen_q:
            continue
        seen_q.add(key)
        deduped_q.append(q)
    final_queries = deduped_q
    random.shuffle(final_queries)

    result = {
        "persona_name": persona["name"],
        "sites": final_sites,
        "queries": final_queries,
        "custom_text": custom_text,
        "interest_keywords": list(persona.get("interest_keywords", [])),
        "link_bias": dict(persona.get("link_bias", {})),
        "priority_hosts": list(persona.get("priority_hosts", [])),
        "late_hosts": list(persona.get("late_hosts", [])),
        "skip_auth_forms": bool(persona.get("skip_auth_forms", False)),
    }

    logger.info(
        f"Profile {profile_id} → {persona['name']} "
        f"({len(final_sites)} sites, {len(final_queries)} queries)"
        + (f" | focus: '{custom_text[:30]}'" if custom_text else "")
    )
    return result


def _build_custom_queries(persona: dict, custom_text: str, queries_out: list):
    text = (custom_text or "").strip()
    if not text:
        return
    for tmpl in persona.get("base_queries", []):
        expanded = tmpl.replace("{item}", text)
        if expanded != tmpl:
            queries_out.append(expanded)
    queries_out.extend([
        f"{text} price 2026",
        f"buy {text} cheap",
        f"{text} reddit",
        f"is {text} legit",
        f"best site for {text}",
    ])
